### PR TITLE
Added Timestamp Format Option

### PR DESCRIPTION
**Pull request by MarketingPip**
## Summary

Added option for formatting dates for sitemaps. Users can use this for reference. [Python strftime reference cheatsheet](https://strftime.org/)

You will need to do unit test as I am not familiar with the process. But I have done manual tests for this on my end. 

Argument is added <code>timestamp-format</code> and needs documentation provided for usage. I am using "None" to as a string < I am sure you can provide a better method for doing so. But I just through this together.  

To be honest too - I am committing to this project as I figured it would be useful / hopefully save you some stress one day + I am using this in my project (with some modifications & am hoping maybe can get some help etc if needed directly). I will try to commit and further improvements I come across when possible. 

Hoping this serves some purpose & saves you some strain from needing to figure out the proper match for stripping the time! And hoping to collaborate on some stuff with you in near future if possible! :+1: 

## Closing Issues
None.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cicirello** [comment]
When would someone want to specify a different format? The [sitemap protocol](https://sitemaps.org/faq.html#faq_specifying_time) calls for [W3C Datetime encoding](http://www.w3.org/TR/NOTE-datetime), although it also allows date only as yyyy-mm-dd without the time.

**Comment by MarketingPip** [comment]
@cicirello - that is not true. 

Here are some references to back that claim.

[https://www.w3.org/TR/NOTE-datetime](https://www.w3.org/TR/NOTE-datetime)

> Don't specify the time when you added the article to your sitemap. The Google News crawler accepts any of the following formats: Complete date: YYYY-MM-DD (1997-07-16) Complete date plus hours and minutes: YYYY-MM-DDThh:mmTZD (1997-07-16T19:20+01:00) [Create a Google News Sitemap | Google Search Central  |  Documentation  |  Google Developers](https://developers.google.com/search/docs/advanced/sitemaps/news-sitemap#:~:text=Don't%20specify%20the%20time,%3A20%2B01%3A00))


> [The Web Guy - SEO - XML Sitemap Last Modified Correct Format](https://www.bryan-myers.com/articles/seo/xml-sitemaps/xml-sitemap-last-modified-correct-format/)

**Comment by MarketingPip** [comment]
@cicirello as well - I was possibly going to look at adding some other features, such as priority ranking etc. Tho as said - I will have to do this when I get more time. As well - was hoping to work on a fork with you to make improvements to this in general < and see if you have any ideas on how I can improve the usage of this in my script for users.

**Comment by MarketingPip** [comment]
@cicirello another resource to back my claim [sitemaps.org - Protocol](https://www.sitemaps.org/protocol.html)

**Comment by cicirello** [comment]
@MarketingPip see my original comment. I said the same thing that you just did. The sitemaps protocol allows 2 formats. The W3C Datetime which is what is currently used. And date only with yyyy-mm-dd without the time. A fully configurable date pattern would potentially lead to user-error if they specify some other date format.

I just created an issue based on this to give users option of date only. See #58. Fee free to submit a new PR for that. An input to the action `date-only` with a default of `false`. When user sets `true` only put date in lastmod.

I'm going to close your current PR. Your changes to `action.yml` would totally break the action. That yml file is how the GitHub Actions framework knows the action's unique name, the input variables that are either required or optional, any outputs in provides, and also configures the top level call. You removed all of that and replaced with python. The only change needed in that file is to add the new input variable. Your current PR would become too cluttered if you added additional commits to undo everything you currently have. So submit a new PR if you want to work on #58.

In answer to your question about `.github` directory, it shouldn't be necessary to explicitly ignore it. There shouldn't really be any files in it of a type that the action would try to add to sitemap. It is mostly `.yml` files for configuring github related stuff. Although if you've discovered some configuration file of a type usually in sitemap, then a way to ignore that directory could be useful.

**Comment by MarketingPip** [comment]
@cicirello Wow, jeez. Don't know what happened to the action.yaml I had added my variable needed and seems I replaced it with the same Py script! (maybe due to a lack of sleep etc here).

I will make the new PR - with only TWO options. And the changes only in one commit. Expect a improved PR with the same feature added with all your points addressed.

**Pull request closed without merging**
